# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20160519_1618'),
        ('qa', '0002_auto_20160519_1026'),
    ]

    operations = [
    ]
